### ISSUE TITLE
GitHub oAuth Connection

### ISSUE THREAD

**Issue by BehrRiley** [b-Universe/b-network#5]
# Authorizing
In reference to [documentation](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps#1-request-a-users-github-identity):

## Initiate authorization
Request details:
`- define url https<&co>//github.com/login/oauth/authorize`
i think we need our authorization?
```yml
- definemap headers:
      Authorization: <secret[github_api_token]>
      User-Agent: B
      Content-Type: Application/json
```
```yml
- define uuid <util.random.duuid>
- definemap data:
    client_id: <secret[github_client_id]>
    redirect_uri: https<&co>//api.behr.dev/github_oauth
    scopes:
    - public_repo
    state: <[uuid]>
```
`- ~webget <[url]> headers:<[headers]> data:<[data].to_json> save:response method:get`

## Redirect token
use `<entry[response].result.parse_yaml.get[code]>` to find the `code` access token, and then post it to:
`- define url https://github.com/login/oauth/access_token`;
check with:
`<entry[response].result.parse_yaml.get[code].if_null[null]>`
redirect token back with:
```yml
- definemap data:
    client_id: <secret[github_client_id]>
    client_secret: <secret[github_client_secret]>
    code: <[code]>
    redirect_uri: https<&co>//api.behr.dev/github_oauth
```
`- ~webget <[url]> headers:<[headers]> data:<[data].to_json> save:response method:get`

From here we can use the `public_repo` scope to fork the relevant repositories and star the others
the `https://api.github.com/user` endpoint will tell us what repositories they have to skip the forking process
