### ISSUE TITLE
Discord oAuth Connection (Draft)

### ISSUE THREAD

**Issue by BehrRiley** [b-Universe/b-network#6]
# Authorizing
In reference to [documentation](https://discord.com/developers/docs/topics/oauth2):

## Initiate authorization
Request details:
`- define url https<&co>//discord.com/oauth2/authorize`
i think we need our authorization?
```yml
- definemap headers:
      Authorization: <secret[cbot]>
      User-Agent: B
      Content-Type: Application/json
```
```yml
- define uuid <util.random.duuid>
- definemap data:
    client_id: <secret[discord_client_id]>
    redirect_uri: https<&co>//api.behr.dev/oAuth/Discord
    scopes:
      # required for name
    - identify
      # good for players to serve an invite if theyre not already in b
    - guilds
      # helpful for checking the user's role in Minecraft server's Discord guilds; great for developers
    - guilds.members.read
    state: <[uuid]>
```
`- ~webget <[url]> headers:<[headers]> data:<[data].to_json> save:response method:get`

## Redirect token
use `<entry[response].result.parse_yaml.get[code]>` to find the `code` access token, and then post it to:
`- define url https<&co>//discord.com/api/oauth2/token`;
check with:
`<entry[response].result.parse_yaml.get[code].if_null[null]>`
redirect token back with:
```yml
- definemap data:
    grant_type: authorization_code
    code: <[code]>
    redirect_uri: https<&co>//api.behr.dev/discord_oauth
```
`- ~webget <[url]> headers:<[headers]> data:<[data].to_json> save:response method:get`
